import type { World } from './types';

export const WORLDS: World[] = [
  // ========== FREE WORLDS ==========
  {
    id: 'critter_cove',
    name: 'Critter Cove',
    tagline: 'Cozy animals & tiny friends',
    color: 'meadow',
    icon: '🐰',
    unlocked: true,
    tier: 'free',
    lessons: [
      'critter_cove_01', 'critter_cove_02', 'critter_cove_03',
      'critter_cove_04', 'critter_cove_05', 'critter_cove_06',
      'critter_cove_07', 'critter_cove_08',
    ],
  },
  {
    id: 'sparkle_kingdom',
    name: 'Sparkle Kingdom',
    tagline: 'Crowns, unicorns & dreamy castles',
    color: 'berry',
    icon: '👑',
    unlocked: true,
    tier: 'free',
    lessons: [
      'sparkle_kingdom_01', 'sparkle_kingdom_02', 'sparkle_kingdom_03',
      'sparkle_kingdom_04', 'sparkle_kingdom_05',
    ],
  },
  {
    id: 'star_hop',
    name: 'Star Hop',
    tagline: 'Rockets, moons & outer-space pals',
    color: 'sky',
    icon: '🚀',
    unlocked: true,
    tier: 'free',
    lessons: ['star_hop_01', 'star_hop_02', 'star_hop_03'],
  },
  {
    id: 'mermaid_lagoon',
    name: 'Mermaid Lagoon',
    tagline: 'Shimmery tails & ocean treasures',
    color: 'sky',
    icon: '🧜‍♀️',
    unlocked: true,
    tier: 'free',
    lessons: ['mermaid_lagoon_01', 'mermaid_lagoon_02', 'mermaid_lagoon_03'],
  },
  // v14a: NEW free worlds
  {
    id: 'pet_parade',
    name: 'Pet Parade',
    tagline: 'Cuddly pets & furry pals',
    color: 'coral',
    icon: '🐶',
    unlocked: true,
    tier: 'free',
    lessons: ['pet_parade_01', 'pet_parade_02', 'pet_parade_03', 'pet_parade_04'],
  },
  {
    id: 'weather_wonders',
    name: 'Weather Wonders',
    tagline: 'Sunny skies, rainy days & rainbows',
    color: 'sky',
    icon: '🌈',
    unlocked: true,
    tier: 'free',
    lessons: ['weather_wonders_01', 'weather_wonders_02', 'weather_wonders_03', 'weather_wonders_04'],
  },
  {
    id: 'bug_buddies',
    name: 'Bug Buddies',
    tagline: 'Friendly insects & tiny critters',
    color: 'meadow',
    icon: '🐝',
    unlocked: true,
    tier: 'free',
    lessons: ['bug_buddies_01', 'bug_buddies_02', 'bug_buddies_03', 'bug_buddies_04'],
  },
  {
    id: 'shape_shop',
    name: 'Shape Shop',
    tagline: 'Squares, stars & happy shapes',
    color: 'sparkle',
    icon: '⭐',
    unlocked: true,
    tier: 'free',
    lessons: ['shape_shop_01', 'shape_shop_02', 'shape_shop_03', 'shape_shop_04'],
  },
  {
    id: 'garden_patch',
    name: 'Garden Patch',
    tagline: 'Flowers, fruits & growing things',
    color: 'meadow',
    icon: '🌷',
    unlocked: true,
    tier: 'free',
    lessons: ['garden_patch_01', 'garden_patch_02', 'garden_patch_03', 'garden_patch_04'],
  },
  // ========== PREMIUM WORLDS ==========
  {
    id: 'dino_land',
    name: 'Dino Land',
    tagline: 'Prehistoric pals & ancient adventures',
    color: 'meadow',
    icon: '🦕',
    unlocked: true,
    tier: 'premium',
    lessons: ['dino_land_01', 'dino_land_02', 'dino_land_03'],
  },
  {
    id: 'fairy_garden',
    name: 'Fairy Garden',
    tagline: 'Pixies, flowers & enchanted blooms',
    color: 'berry',
    icon: '🧚',
    unlocked: true,
    tier: 'premium',
    lessons: ['fairy_garden_01', 'fairy_garden_02', 'fairy_garden_03'],
  },
  {
    id: 'food_friends',
    name: 'Food Friends',
    tagline: 'Smiley snacks & adorable treats',
    color: 'coral',
    icon: '🍰',
    unlocked: true,
    tier: 'premium',
    lessons: ['food_friends_01', 'food_friends_02', 'food_friends_03'],
  },
  {
    id: 'vehicle_village',
    name: 'Vehicle Village',
    tagline: 'Wheels, wings & things that zoom',
    color: 'sparkle',
    icon: '🚗',
    unlocked: true,
    tier: 'premium',
    lessons: ['vehicle_village_01', 'vehicle_village_02', 'vehicle_village_03'],
  },
  // v14b: NEW premium worlds
  {
    id: 'sea_adventure',
    name: 'Sea Adventure',
    tagline: 'Pirate ships, lighthouses & buried treasure',
    color: 'sky',
    icon: '⚓',
    unlocked: true,
    tier: 'premium',
    lessons: ['sea_adventure_01', 'sea_adventure_02', 'sea_adventure_03', 'sea_adventure_04'],
  },
  {
    id: 'robot_workshop',
    name: 'Robot Workshop',
    tagline: 'Robots, gears & cool gadgets',
    color: 'sparkle',
    icon: '🤖',
    unlocked: true,
    tier: 'premium',
    lessons: ['robot_workshop_01', 'robot_workshop_02', 'robot_workshop_03', 'robot_workshop_04'],
  },
  {
    id: 'bakery_sweets',
    name: 'Bakery Sweets',
    tagline: 'Cupcakes, donuts & yummy treats',
    color: 'coral',
    icon: '🧁',
    unlocked: true,
    tier: 'premium',
    lessons: ['bakery_sweets_01', 'bakery_sweets_02', 'bakery_sweets_03', 'bakery_sweets_04'],
  },
  {
    id: 'toy_box',
    name: 'Toy Box',
    tagline: 'Teddy bears, blocks & playful things',
    color: 'berry',
    icon: '🧸',
    unlocked: true,
    tier: 'premium',
    lessons: ['toy_box_01', 'toy_box_02', 'toy_box_03', 'toy_box_04'],
  },
  {
    id: 'holiday_magic',
    name: 'Holiday Magic',
    tagline: 'Snowmen, pumpkins & festive fun',
    color: 'meadow',
    icon: '🎃',
    unlocked: true,
    tier: 'premium',
    lessons: ['holiday_magic_01', 'holiday_magic_02', 'holiday_magic_03', 'holiday_magic_04'],
  },
];

export function getWorld(id: string): World | undefined {
  return WORLDS.find((w) => w.id === id);
}

export function getFreeWorlds(): World[] {
  return WORLDS.filter((w) => w.tier === 'free');
}

export function getPremiumWorlds(): World[] {
  return WORLDS.filter((w) => w.tier === 'premium');
}
